services:
 vite_docker:
   image: node:alpine
   container_name: vite_docker
   entrypoint: /bin/sh
   ports:
     - "8002:8002"
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
   dns:
     - 8.8.8.8
     - 8.8.4.4
   network_mode: bridge